/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    PokerVault: {
      address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_operator",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tournamentId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "seatIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "wallet",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "AgentEntered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tournamentId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "buyIn",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "maxPlayers",
              type: "uint8",
            },
          ],
          name: "TournamentCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tournamentId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "winningSeat",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "winner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "payout",
              type: "uint256",
            },
          ],
          name: "TournamentSettled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tournamentId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "playerCount",
              type: "uint256",
            },
          ],
          name: "TournamentStarted",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "buyIn",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "maxPlayers",
              type: "uint8",
            },
          ],
          name: "createTournament",
          outputs: [
            {
              internalType: "uint256",
              name: "tournamentId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tournamentId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "systemPrompt",
              type: "string",
            },
          ],
          name: "enterTournament",
          outputs: [
            {
              internalType: "uint256",
              name: "seatIndex",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tournamentId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "seatIndex",
              type: "uint256",
            },
          ],
          name: "getTournamentAgent",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "wallet",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "systemPrompt",
                  type: "string",
                },
              ],
              internalType: "struct PokerVault.Agent",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tournamentId",
              type: "uint256",
            },
          ],
          name: "getTournamentAgents",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "wallet",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "systemPrompt",
                  type: "string",
                },
              ],
              internalType: "struct PokerVault.Agent[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tournamentId",
              type: "uint256",
            },
          ],
          name: "getTournamentCreator",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "nextTournamentId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "operator",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_operator",
              type: "address",
            },
          ],
          name: "setOperator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tournamentId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "winningSeat",
              type: "uint256",
            },
          ],
          name: "settleTournament",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tournamentId",
              type: "uint256",
            },
          ],
          name: "startTournament",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "tournaments",
          outputs: [
            {
              internalType: "uint256",
              name: "buyIn",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "prizePool",
              type: "uint256",
            },
            {
              internalType: "enum PokerVault.TournamentStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "maxPlayers",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {
        owner: "@openzeppelin/contracts/access/Ownable.sol",
        renounceOwnership: "@openzeppelin/contracts/access/Ownable.sol",
        transferOwnership: "@openzeppelin/contracts/access/Ownable.sol",
      },
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
